[Interface]
PrivateKey = <CHAVE_PRIVADA_SISTEMA>
Address = 10.0.0.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = <CHAVE_SERVIDOR_ZELUS>
Endpoint = 192.168.0.8:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
